#[rustfmt::skip]
pub const WORDS: [&str; 256] = [
    "able", "acid", "also", "apex", "aqua", "arch", "atom", "aunt",
    "away", "axis", "back", "bald", "barn", "belt", "beta", "bias",
    "blue", "body", "brag", "brew", "bulb", "buzz", "calm", "cash",
    "cats", "chef", "city", "claw", "code", "cola", "cook", "cost",
    "crux", "curl", "cusp", "cyan", "dark", "data", "days", "deli",
    "dice", "diet", "door", "down", "draw", "drop", "drum", "dull",
    "duty", "each", "easy", "echo", "edge", "epic", "even", "exam",
    "exit", "eyes", "fact", "fair", "fern", "figs", "film", "fish",
    "fizz", "flap", "flew", "flux", "foxy", "free", "frog", "fuel",
    "fund", "gala", "game", "gear", "gems", "gift", "girl", "glow",
    "good", "gray", "grim", "guru", "gush", "gyro", "half", "hang",
    "hard", "hawk", "heat", "help", "high", "hill", "holy", "hope",
    "horn", "huts", "iced", "idea", "idle", "inch", "inky", "into",
    "iris", "iron", "item", "jade", "jazz", "join", "jolt", "jowl",
    "judo", "jugs", "jump", "junk", "jury", "keep", "keno", "kept",
    "keys", "kick", "kiln", "king", "kite", "kiwi", "knob", "lamb",
    "lava", "lazy", "leaf", "legs", "liar", "limp", "lion", "list",
    "logo", "loud", "love", "luau", "luck", "lung", "main", "many",
    "math", "maze", "memo", "menu", "meow", "mild", "mint", "miss",
    "monk", "nail", "navy", "need", "news", "next", "noon", "note",
    "numb", "obey", "oboe", "omit", "onyx", "open", "oval", "owls",
    "paid", "part", "peck", "play", "plus", "poem", "pool", "pose",
    "puff", "puma", "purr", "quad", "quiz", "race", "ramp", "real",
    "redo", "rich", "road", "rock", "roof", "ruby", "ruin", "runs",
    "rust", "safe", "saga", "scar", "sets", "silk", "skew", "slot",
    "soap", "solo", "song", "stub", "surf", "swan", "taco", "task",
    "taxi", "tent", "tied", "time", "tiny", "toil", "tomb", "toys",
    "trip", "tuna", "twin", "ugly", "undo", "unit", "urge", "user",
    "vast", "very", "veto", "vial", "vibe", "view", "visa", "void",
    "vows", "wall", "wand", "warm", "wasp", "wave", "waxy", "webs",
    "what", "when", "whiz", "wolf", "work", "yank", "yawn", "yell",
    "yoga", "yurt", "zaps", "zero", "zest", "zinc", "zone", "zoom",
];

#[rustfmt::skip]
pub const MINIMALS: [&str; 256] = [
    "ae", "ad", "ao", "ax", "aa", "ah", "am", "at",
    "ay", "as", "bk", "bd", "bn", "bt", "ba", "bs",
    "be", "by", "bg", "bw", "bb", "bz", "cm", "ch",
    "cs", "cf", "cy", "cw", "ce", "ca", "ck", "ct",
    "cx", "cl", "cp", "cn", "dk", "da", "ds", "di",
    "de", "dt", "dr", "dn", "dw", "dp", "dm", "dl",
    "dy", "eh", "ey", "eo", "ee", "ec", "en", "em",
    "et", "es", "ft", "fr", "fn", "fs", "fm", "fh",
    "fz", "fp", "fw", "fx", "fy", "fe", "fg", "fl",
    "fd", "ga", "ge", "gr", "gs", "gt", "gl", "gw",
    "gd", "gy", "gm", "gu", "gh", "go", "hf", "hg",
    "hd", "hk", "ht", "hp", "hh", "hl", "hy", "he",
    "hn", "hs", "id", "ia", "ie", "ih", "iy", "io",
    "is", "in", "im", "je", "jz", "jn", "jt", "jl",
    "jo", "js", "jp", "jk", "jy", "kp", "ko", "kt",
    "ks", "kk", "kn", "kg", "ke", "ki", "kb", "lb",
    "la", "ly", "lf", "ls", "lr", "lp", "ln", "lt",
    "lo", "ld", "le", "lu", "lk", "lg", "mn", "my",
    "mh", "me", "mo", "mu", "mw", "md", "mt", "ms",
    "mk", "nl", "ny", "nd", "ns", "nt", "nn", "ne",
    "nb", "oy", "oe", "ot", "ox", "on", "ol", "os",
    "pd", "pt", "pk", "py", "ps", "pm", "pl", "pe",
    "pf", "pa", "pr", "qd", "qz", "re", "rp", "rl",
    "ro", "rh", "rd", "rk", "rf", "ry", "rn", "rs",
    "rt", "se", "sa", "sr", "ss", "sk", "sw", "st",
    "sp", "so", "sg", "sb", "sf", "sn", "to", "tk",
    "ti", "tt", "td", "te", "ty", "tl", "tb", "ts",
    "tp", "ta", "tn", "uy", "uo", "ut", "ue", "ur",
    "vt", "vy", "vo", "vl", "ve", "vw", "va", "vd",
    "vs", "wl", "wd", "wm", "wp", "we", "wy", "ws",
    "wt", "wn", "wz", "wf", "wk", "yk", "yn", "yl",
    "ya", "yt", "zs", "zo", "zt", "zc", "ze", "zm",
];

#[rustfmt::skip]
pub const BYTES_INDEXED_BY_HASH: [Option<u8>; 628] = [
    None, Some(101), None, None, None, None, Some(82), None, Some(41),
    Some(89), Some(127), None, None, Some(17), Some(65), None, Some(27),
    None, Some(124), None, Some(93), None, Some(57), None, Some(21), None,
    None, Some(32), Some(85), None, None, None, Some(137), Some(56), None,
    None, Some(59), None, Some(26), None, Some(123), Some(44), Some(96),
    Some(138), None, None, None, Some(61), None, None, None, None, None,
    None, Some(130), None, Some(106), Some(149), Some(58), Some(115),
    Some(160), Some(75), Some(125), Some(48), Some(91), Some(141), None,
    Some(105), Some(145), None, Some(111), None, Some(76), None, None,
    None, None, None, Some(103), None, None, None, Some(155), Some(77),
    Some(121), None, None, None, Some(50), None, None, Some(66),
    Some(109), Some(159), Some(83), None, None, Some(97), None,
    Some(177), None, Some(144), Some(67), Some(112), None, None, None,
    None, Some(90), Some(140), None, None, None, Some(68), Some(114),
    None, Some(79), Some(122), Some(162), None, None, None, Some(104),
    None, Some(64), None, None, None, Some(118), None, None, None,
    Some(168), None, Some(152), None, None, None, Some(81), Some(117),
    None, None, Some(134), Some(175), None, None, None, Some(113), None,
    None, None, None, None, Some(136), Some(176), None, None, Some(179),
    Some(110), None, None, None, None, Some(94), Some(133), None, None,
    Some(142), None, None, Some(153), None, Some(120), None, Some(194),
    None, None, None, Some(146), None, None, None, Some(186),
    Some(119), None, Some(203), Some(132), None, Some(102), None, None,
    None, Some(158), Some(181), None, Some(166), None, Some(131), None,
    Some(217), None, None, None, None, Some(188), None, None, None,
    Some(135), Some(170), Some(214), None, None, Some(116), None, None,
    None, Some(165), Some(193), Some(139), Some(174), None, Some(151),
    None, Some(108), None, Some(185), None, None, Some(204), None,
    Some(173), Some(210), Some(150), None, None, None, None, None, None,
    Some(202), None, None, Some(211), Some(147), None, None, Some(156),
    None, Some(230), None, None, None, None, None, None, None, None,
    Some(157), Some(187), None, None, None, Some(129), None, None,
    Some(148), None, Some(222), None, Some(183), None, Some(167), None,
    None, None, None, None, None, None, None, None, Some(231),
    Some(163), Some(197), None, Some(178), Some(208), Some(143), None,
    None, None, Some(190), Some(228), None, None, None, Some(172), None,
    None, None, None, None, Some(184), None, None, None, Some(234),
    Some(169), Some(207), None, None, None, Some(154), Some(182), None,
    None, Some(205), Some(237), None, Some(213), None, None, None,
    Some(248), None, None, Some(164), Some(201), Some(243), None, None,
    None, None, None, None, None, None, Some(161), Some(200), None,
    None, Some(218), None, None, None, None, Some(191), None, None,
    None, None, Some(4), Some(206), None, None, None, None, Some(192),
    None, None, Some(195), None, Some(171), Some(216), None, None,
    None, None, None, Some(227), Some(253), Some(196), None, None,
    None, None, Some(14), Some(220), None, None, None, None, Some(199),
    Some(244), Some(1), None, None, Some(20), None, None, None, None,
    Some(254), None, Some(233), Some(0), Some(215), None, Some(180),
    None, None, Some(29), Some(226), None, None, Some(235), None,
    Some(209), None, Some(11), Some(223), None, Some(189), None, None,
    Some(198), Some(241), None, None, None, Some(16), None, None, None,
    None, None, Some(37), None, Some(5), None, None, None, Some(221),
    Some(245), None, None, None, None, Some(236), None, None, None,
    Some(18), None, Some(247), Some(28), Some(232), None, None, None,
    None, None, None, None, None, None, Some(25), Some(224), None,
    None, None, None, Some(212), None, None, None, Some(246), None,
    None, None, Some(40), Some(239), None, Some(53), None, None, None,
    None, Some(23), None, Some(255), None, Some(240), Some(6), None,
    None, Some(10), Some(219), None, None, Some(229), None, None, None,
    None, Some(52), None, None, None, None, None, Some(73), Some(251),
    None, None, Some(2), None, None, None, Some(72), None, Some(30),
    Some(225), None, Some(39), None, None, None, None, Some(12),
    Some(69), None, Some(33), None, None, None, None, None, Some(49),
    None, None, None, Some(249), Some(22), Some(80), None, Some(36),
    Some(238), None, None, None, None, Some(70), None, Some(35),
    Some(74), Some(250), Some(47), Some(242), Some(9), None, Some(99),
    None, Some(63), None, None, None, Some(252), Some(46), Some(88),
    Some(7), None, None, None, None, None, Some(34), None, None,
    Some(43), Some(95), None, None, None, Some(15), None, None, None,
    Some(84), None, None, Some(86), None, Some(55), Some(98), Some(13),
    None, None, None, None, None, Some(45), Some(87), None, Some(54),
    Some(100), None, Some(71), None, Some(24), None, None, None,
    Some(92), Some(3), Some(51), None, None, Some(62), None, Some(31),
    None, Some(126), Some(42), None, Some(8), None, None, Some(19),
    Some(60), Some(107), None, Some(78), None, Some(38), None,
    Some(128),
];
