name: Format doc examples

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - run: rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
      - run: cargo fmt --check -- --config-path rustfmt.toml.nightly
