name: no-std

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  no-std:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv6m-none-eabi
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target thumbv6m-none-eabi --no-default-features
